openapi: 3.1.0
info:
  version: 1.0.0
  title: Orders app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation for the bot
tags:
  - name: Order
    description: Operations about order.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  # - url: https://swagger-contacts.onrender.com
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
